In [ ]:
import numpy as np
X = [[np.nan, 5, 6], [7, 8, np.nan], [1, 2, 3]]

In [ ]:
from sklearn.impute import SimpleImputer
y = SimpleImputer(missing_values = np.nan, strategy = 'mean')
y.fit(X)
print(y.transform(X))

[[4.  5.  6. ]
 [7.  8.  4.5]
 [1.  2.  3. ]]


In [ ]:
from sklearn.impute import SimpleImputer
y = SimpleImputer(missing_values = np.nan, strategy = 'median')
y.fit(X)
print(X)
print(y.transform(X))

[[nan, 5, 6], [7, 8, nan], [1, 2, 3]]
[[4.  5.  6. ]
 [7.  8.  4.5]
 [1.  2.  3. ]]


In [ ]:
Z = [[np.nan, 5, 6], [7, 8, np.nan], [1, 2, 3], [4, 7, 9]]
from sklearn.impute import SimpleImputer
y = SimpleImputer(missing_values = np.nan, strategy = 'median')
y.fit(Z)
print(Z)
print(y.transform(Z))

[[nan, 5, 6], [7, 8, nan], [1, 2, 3], [4, 7, 9]]
[[4. 5. 6.]
 [7. 8. 6.]
 [1. 2. 3.]
 [4. 7. 9.]]


In [ ]:
Z = [[np.nan, 5, 6], [7, 8, np.nan], [1, 2, 3], [4, 7, 9]]
from sklearn.impute import SimpleImputer
y = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
y.fit(Z)
print(Z)
print(y.transform(Z))

[[nan, 5, 6], [7, 8, nan], [1, 2, 3], [4, 7, 9]]
[[1. 5. 6.]
 [7. 8. 3.]
 [1. 2. 3.]
 [4. 7. 9.]]


In [ ]:
Z = [[np.nan, 5, 6], [4, 8, np.nan], [1, 2, 3], [4, 7, 9]]
from sklearn.impute import SimpleImputer
y = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
y.fit(Z)
print(Z)
print(y.transform(Z))

[[nan, 5, 6], [4, 8, nan], [1, 2, 3], [4, 7, 9]]
[[4. 5. 6.]
 [4. 8. 3.]
 [1. 2. 3.]
 [4. 7. 9.]]


In [ ]:
Z = [[np.nan, 5, 6], [4, 8, np.nan], [1, 2, 3], [4, 7, 9]]
from sklearn.impute import SimpleImputer
y = SimpleImputer(missing_values = np.nan, strategy = 'constant')
y.fit(Z)
print(Z)
print(y.transform(Z))

[[nan, 5, 6], [4, 8, nan], [1, 2, 3], [4, 7, 9]]
[[0. 5. 6.]
 [4. 8. 0.]
 [1. 2. 3.]
 [4. 7. 9.]]
