#K-fold cross validation

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [ ]:
from sklearn.ensemble import StackingRegressor
level0=list()
level0.append(('lr',LinearRegression()))
level0.append(('dt',DecisionTreeRegressor()))
level1=LinearRegression()
model_en=StackingRegressor(estimators=level0,final_estimator=level1,cv=5)

### diabetes dataset

In [ ]:
from sklearn.datasets import load_diabetes

In [ ]:
X,y=load_diabetes(return_X_y=True)

In [ ]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [ ]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
pca1=pca.fit_transform(X)
pca1

array([[ 2.79306207e-02, -9.26011612e-02],
       [-1.34686052e-01,  6.52634060e-02],
       [ 1.29447396e-02, -7.77641691e-02],
       [ 2.34543980e-03,  1.81819367e-02],
       [-3.59806910e-02,  3.86213572e-02],
       [-1.88660280e-01, -1.81251413e-02],
       [-9.48347610e-02, -3.83155499e-02],
       [ 9.87389258e-02,  8.69453424e-02],
       [ 2.86833351e-02, -4.19169143e-02],
       [-1.00910711e-02, -2.34450670e-02],
       [-1.83419418e-01, -7.28738089e-02],
       [ 1.88796730e-02, -3.00873701e-02],
       [-7.59323171e-02,  4.66838722e-02],
       [ 1.51473512e-02, -3.09692487e-02],
       [-8.01694940e-02,  8.64707740e-02],
       [ 1.40488092e-01,  4.51897240e-02],
       [ 7.58600302e-03,  4.33946961e-02],
       [ 1.08839198e-01, -7.06819254e-03],
       [-5.49947993e-02, -2.03725705e-02],
       [-8.42651351e-02,  4.41806793e-02],
       [-9.55955468e-02, -1.37941404e-02],
       [-9.18719735e-02, -3.95423697e-02],
       [-7.97268029e-02,  3.42316116e-02],
       [ 1.

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
for train,test in kf.split(X,y):
    Xtrain,Xtest=X[train],X[test]
    ytrain,ytest=y[train],y[test]

In [ ]:
print(Xtrain.shape,ytrain.shape)
print(Xtest.shape,ytest.shape)

(354, 10) (354,)
(88, 10) (88,)


In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(Xtrain,ytrain)

LinearRegression()

In [ ]:
ypred=model.predict(Xtest)
ypred

array([191.42755525, 133.04877448,  91.97677251, 198.85251886,
        54.98917741, 173.71496126, 196.45853504, 120.51068765,
       233.23043101, 163.51698175, 161.25297652, 163.87635245,
       253.65571515, 255.59408899, 197.81068341, 185.44645028,
        60.136369  , 194.75215437, 109.34153649, 143.03292209,
       127.92878888, 176.04394067, 209.93507631, 166.33590143,
       162.17984648, 137.52983423, 174.20311213,  74.27388858,
       249.47602759, 113.96862315, 108.93850616, 138.30775304,
       110.87297284,  95.73780182, 159.50300881,  75.56060774,
       254.52713294,  57.2151258 ,  99.57030731, 101.80895415,
       261.24938284, 168.81352273,  64.20043431, 183.10714025,
       169.90316133, 187.00854392, 184.8058785 ,  90.37629602,
       148.74592464, 251.58873636, 198.12771061, 279.87044377,
        51.41253122, 175.31773735, 201.50171976, 170.2097595 ,
       155.29608618, 152.87506316, 232.74795372, 122.87668768,
       163.18303141, 172.87883213, 225.2838219 , 152.36

In [ ]:
from sklearn import metrics
import numpy as np
print("Mean Absolute Error= ",metrics.mean_absolute_error(ypred,ytest))
print("Mean Squared Error= ",metrics.mean_squared_error(ypred,ytest))
print("Root Mean Square Error= ",np.sqrt(metrics.mean_absolute_error(ypred,ytest)))

Mean Absolute Error=  42.38729269073616
Mean Squared Error=  2910.2069332665283
Root Mean Square Error=  6.5105524105667225


### digits dataset

In [ ]:
from sklearn.datasets import load_digits
digits=load_digits()
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [ ]:
X=digits.data
y=digits.target

In [ ]:
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [ ]:
import pandas as pd
df_x=pd.DataFrame(X)
df_x

0    1     2     3     4     5    6    7    8    9   ...   54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  4.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  1.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  8.0  0.0   

       56   57   58    59    60    61   62   63  
0     0.0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1     0.0  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2     0.0  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3     0.0  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4     0.0  0.0  0.0   2.0  16.0   4.0  0.0  0.0  
...   ...  ...  ...   ...   ...   ...  ...  ...  
1792  0.0  0.0  2.0  14.0  15.0   9.0  0.0  0.0  
1793  0.0  0.0  6.0  16.0  14.0   6.0  0.0  0.0  
1794  0.0  0.0  2.0   9.0  13.0   6.0  0.0  0.0  
1795  0.0  0.0  5.0  12.0  16.0  12.0  0.0  0.0  
1796  0.0  1.0  8.0  12.0  14.0  12.0  1.0  0.0  

[1797 rows x 64 columns]

In [ ]:
df_y=pd.DataFrame(y)
df_y

0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [ ]:
data=pd.concat([df_x,df_y],axis=1)
data

0    1     2     3     4     5    6    7    8    9   ...   55   56  \
0     0.0  0.0   5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  0.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
...   ...  ...   ...   ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   
1792  0.0  0.0   4.0  10.0  13.0   6.0  0.0  0.0  0.0  1.0  ...  0.0  0.0   
1793  0.0  0.0   6.0  16.0  13.0  11.0  1.0  0.0  0.0  0.0  ...  0.0  0.0   
1794  0.0  0.0   1.0  11.0  15.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1795  0.0  0.0   2.0  10.0   7.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0   
1796  0.0  0.0  10.0  14.0   8.0   1.0  0.0  0.0  0.0  2.0  ...  0.0  0.0   

       57   58    59    60    61   62   63  0   
0     0.0  6.0  13.0  10.0   0.0  0.0  0.0   0  
1     0.0  0.0  11.0  16.0  10.0  0.0  0.0   1  
2     0.0  0.0   3.0  11.0  16.0  9.0  0.0   2  
3     0.0  7.0  13.0  13.0   9.0  0.0  0.0   3  
4     0.0  0.0   2.0  16.0   4.0  0.0  0.0   4  
...   ...  ...   ...   ...   ...  ...  ...  ..  
1792  0.0  2.0  14.0  15.0   9.0  0.0  0.0   9  
1793  0.0  6.0  16.0  14.0   6.0  0.0  0.0   0  
1794  0.0  2.0   9.0  13.0   6.0  0.0  0.0   8  
1795  0.0  5.0  12.0  16.0  12.0  0.0  0.0   9  
1796  1.0  8.0  12.0  14.0  12.0  1.0  0.0   8  

[1797 rows x 65 columns]

In [ ]:
data.shape

(1797, 65)

In [ ]:
data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
60    0
61    0
62    0
63    0
0     0
Length: 65, dtype: int64

In [ ]:
digits=load_digits(as_frame=True)
print(digits)
type(digits)

{'data':       pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        

sklearn.utils.Bunch

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df_x=scaler.fit_transform(df_x)
df_x

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=30)
pca=pca.fit_transform(df_x)
pca

array([[ 1.91421456, -0.95450254, -3.94603585, ...,  0.1770879 ,
         0.3339638 , -0.26434912],
       [ 0.58897935,  0.92463529,  3.92474745, ..., -0.8650948 ,
        -0.70873138, -0.2948506 ],
       [ 1.30204011, -0.31718792,  3.02333639, ...,  0.23682882,
        -0.38505916,  1.47073694],
       ...,
       [ 1.02259866, -0.14791234,  2.46997926, ..., -0.26044662,
         0.33624301, -0.18000867],
       [ 1.07605473, -0.38090595, -2.45548972, ...,  0.96832318,
         0.26513408, -0.66818083],
       [-1.25770039, -2.22759199,  0.28363247, ...,  0.96151194,
         0.55440609,  0.48750923]])

In [ ]:
pca.shape

(1797, 30)

In [ ]:
df_x=pd.DataFrame(pca)
df_x

0         1         2         3         4         5         6   \
0     1.914215 -0.954503 -3.946036  2.028718 -0.267119  0.530292 -1.415280   
1     0.588979  0.924635  3.924747 -1.779857 -0.993398 -0.675667  1.878554   
2     1.302040 -0.317188  3.023336 -2.043391 -2.081136  0.935044 -1.296257   
3    -3.020769 -0.868774 -0.801743 -2.187042 -0.556737  0.727028  0.959803   
4     4.528946 -1.093478  0.973125 -1.419486 -1.715267  1.431803  1.073655   
...        ...       ...       ...       ...       ...       ...       ...   
1792  0.104331  0.255025 -3.765858 -1.947004 -0.190116 -0.555739  0.531244   
1793  2.423233 -1.429609 -3.045248  2.632091 -0.822965  0.004104 -1.107025   
1794  1.022599 -0.147912  2.469979 -0.620307 -0.971981 -0.007425  0.381274   
1795  1.076055 -0.380906 -2.455490 -1.312019  0.253537 -0.638349  1.034444   
1796 -1.257700 -2.227592  0.283632 -0.127076 -1.570123  2.342897 -0.383043   

            7         8         9   ...        20        21        22  \
0     1.496040  0.124809 -0.822117  ...  0.455625 -0.562546  0.516523   
1     0.556445  1.080117  0.087649  ...  0.905095  0.242425 -0.493850   
2     1.156007  0.785303 -1.099837  ... -0.523742 -0.069905 -1.247864   
3    -1.382808  0.258685  0.744522  ...  0.568844  0.159910  0.593834   
4    -0.968075 -1.659575  1.174848  ...  0.488434  0.194696  0.933912   
...        ...       ...       ...  ...       ...       ...       ...   
1792  0.476463  1.152419 -0.473120  ...  0.032449  0.782389 -0.667174   
1793  2.330987  0.569509 -1.654462  ... -0.967911  0.054914  0.364662   
1794  0.528929  2.054385 -2.036670  ...  0.180219  0.222626  0.067937   
1795  0.763372  1.077579 -0.334636  ... -0.138352  0.431040  1.113517   
1796 -1.200739  0.816448 -1.825574  ... -1.104111  0.283856 -1.049806   

            23        24        25        26        27        28        29  
0    -0.753677 -0.442939  0.741455  0.373177  0.177088  0.333964 -0.264349  
1     0.502423  0.809981  0.090761 -1.553988 -0.865095 -0.708731 -0.294851  
2    -0.395244 -0.398352 -0.126120  0.349660  0.236829 -0.385059  1.470737  
3    -0.526506 -0.049052 -0.511211  0.291293 -0.300491  0.113870 -1.161208  
4    -0.206689  0.486186 -2.122774 -0.009334  0.738559  1.134220 -0.041993  
...        ...       ...       ...       ...       ...       ...       ...  
1792 -0.047538 -0.356895 -0.079581  0.256714  0.120682  0.910843 -0.111789  
1793  0.085034  0.190581 -0.857837  0.200711 -0.601444 -0.674777  0.012337  
1794  0.230082 -0.238671 -1.379180  0.096500 -0.260447  0.336243 -0.180009  
1795  0.322759 -0.907671  1.163485 -0.674197  0.968323  0.265134 -0.668181  
1796 -0.271668 -0.886411 -0.463971 -0.278083  0.961512  0.554406  0.487509  

[1797 rows x 30 columns]

In [ ]:
df_y

0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]

In [ ]:
data=pd.concat([df_x,df_y],axis=1)
data

0         1         2         3         4         5         6   \
0     1.914215 -0.954503 -3.946036  2.028718 -0.267119  0.530292 -1.415280   
1     0.588979  0.924635  3.924747 -1.779857 -0.993398 -0.675667  1.878554   
2     1.302040 -0.317188  3.023336 -2.043391 -2.081136  0.935044 -1.296257   
3    -3.020769 -0.868774 -0.801743 -2.187042 -0.556737  0.727028  0.959803   
4     4.528946 -1.093478  0.973125 -1.419486 -1.715267  1.431803  1.073655   
...        ...       ...       ...       ...       ...       ...       ...   
1792  0.104331  0.255025 -3.765858 -1.947004 -0.190116 -0.555739  0.531244   
1793  2.423233 -1.429609 -3.045248  2.632091 -0.822965  0.004104 -1.107025   
1794  1.022599 -0.147912  2.469979 -0.620307 -0.971981 -0.007425  0.381274   
1795  1.076055 -0.380906 -2.455490 -1.312019  0.253537 -0.638349  1.034444   
1796 -1.257700 -2.227592  0.283632 -0.127076 -1.570123  2.342897 -0.383043   

            7         8         9   ...        21        22        23  \
0     1.496040  0.124809 -0.822117  ... -0.562546  0.516523 -0.753677   
1     0.556445  1.080117  0.087649  ...  0.242425 -0.493850  0.502423   
2     1.156007  0.785303 -1.099837  ... -0.069905 -1.247864 -0.395244   
3    -1.382808  0.258685  0.744522  ...  0.159910  0.593834 -0.526506   
4    -0.968075 -1.659575  1.174848  ...  0.194696  0.933912 -0.206689   
...        ...       ...       ...  ...       ...       ...       ...   
1792  0.476463  1.152419 -0.473120  ...  0.782389 -0.667174 -0.047538   
1793  2.330987  0.569509 -1.654462  ...  0.054914  0.364662  0.085034   
1794  0.528929  2.054385 -2.036670  ...  0.222626  0.067937  0.230082   
1795  0.763372  1.077579 -0.334636  ...  0.431040  1.113517  0.322759   
1796 -1.200739  0.816448 -1.825574  ...  0.283856 -1.049806 -0.271668   

            24        25        26        27        28        29  0   
0    -0.442939  0.741455  0.373177  0.177088  0.333964 -0.264349   0  
1     0.809981  0.090761 -1.553988 -0.865095 -0.708731 -0.294851   1  
2    -0.398352 -0.126120  0.349660  0.236829 -0.385059  1.470737   2  
3    -0.049052 -0.511211  0.291293 -0.300491  0.113870 -1.161208   3  
4     0.486186 -2.122774 -0.009334  0.738559  1.134220 -0.041993   4  
...        ...       ...       ...       ...       ...       ...  ..  
1792 -0.356895 -0.079581  0.256714  0.120682  0.910843 -0.111789   9  
1793  0.190581 -0.857837  0.200711 -0.601444 -0.674777  0.012337   0  
1794 -0.238671 -1.379180  0.096500 -0.260447  0.336243 -0.180009   8  
1795 -0.907671  1.163485 -0.674197  0.968323  0.265134 -0.668181   9  
1796 -0.886411 -0.463971 -0.278083  0.961512  0.554406  0.487509   8  

[1797 rows x 31 columns]